### PR TITLE
fix: Execute ADB commands sequentially to fix mounting issues

### PR DESCRIPTION
**Pull request by ricnava00**
Should solve https://github.com/ReVanced/revanced-cli/issues/267, once https://github.com/ReVanced/revanced-cli/pull/278 is merged

### CODE REVIEW

**Comment by oSumAtrIX** [comment]
Please explain the change, I do not see why these changes make a difference or how they change behaviour.

**Comment by ricnava00** [comment]
As written in the issue, patching with `--mount` freezes instantly. It seems that using `su -h` is the culprit, but I don't know why. Replacing it with `which su` has the same function, it gives a non-0 exit code if su is not found. For some reason this command seems to be unaffected by the hanging issue. I can confirm this works on my device.

The second commit, as I wrote in its description, solves an out-of-order problem. All the commands were run concurrently, without waiting for the previous ones to finish.
So, for example, instead of:
- Push the APK to the temp file
- Move it to the APK's final directory
- Write the mounting script to the temp file
- Move it to the script's final directory
- Execute it
- Open the target app
You could have runs like (as in my case):
- Push the APK to the temp file
- Write the mounting script to the temp file
- Move the temp file, now containing the script, to the APK's final directory
- ...
Which is not the intended result.
Adding waitFor after running each command ensures that it has completed before running the next one

**Review by oSumAtrIX — APPROVED** [review]

**Comment by PalmDevs** [comment]
@ricnava00 `which su` does not return a non-zero exit code when superuser is disallowed for Shell. Any other commands you'd like to suggest? `su -h` freezes for me too only with CLI it seems, not in normal `adb shell`.

**Comment by PalmDevs** [comment]
Okay, so doing the following seems to work for me. Can you confirm with your device too?
```kt
this.startCommand("su -c \"echo test\"", false).waitFor == 0
```

---

With superuser enabled
image

With superuser disabled
image

**Comment by PalmDevs** [comment]
Putting comments inside instead of a command works too:
```kt
this.startCommand("su -c \"# hello world\"", false).waitFor() == 0
```

**Comment by ricnava00** [comment]
Yes, I can confirm this works on my device too

**Pull request merged**
